CREATE TABLE TAI_KHOAN (
  EMAIL VARCHAR2(50) NOT NULL PRIMARY KEY,
  MATKHAU VARCHAR2(200) NOT NULL,
  HOTEN VARCHAR2(50) NOT NULL,
  SDT VARCHAR2(20) NOT NULL,
  ROLE VARCHAR(20) NOT NULL,
  NGAYTAOTK DATE NOT NULL,
  NAMSINH NUMBER(4) NOT NULL,
  CCCD VARCHAR2(15) NOT NULL
);
CREATE TABLE XE (
  MAXE NUMBER(10) NOT NULL PRIMARY KEY,
  THONGTINXE VARCHAR2(2000) NOT NULL,
  CHONGOI VARCHAR2(20) NOT NULL,
  NHIENLIEUTH NUMBER(3,2) NOT NULL,
  NHIENLIEU VARCHAR2(10) NOT NULL,
  HOPSO VARCHAR2(15) NOT NULL,
  GIA NUMBER(10) NOT NULL,
  MOTA VARCHAR2(2000),
  DANHGIA VARCHAR2(200),
  VITRI VARCHAR2(2000),
  ANH VARCHAR2(2000),
  TRANGTHAI VARCHAR2(20) NOT NULL,
  LUOTCHOTHUE NUMBER(10),
  LUOTDANHGIA NUMBER(10),
  DANHGIATRUNGBINH NUMBER(3,2),
  GIAYTOXE VARCHAR2(2000),
  GIACHOTHUE NUMBER(10),
  THONGTINLIENQUAN VARCHAR2(2000),
  DIEUKHOAN VARCHAR2(2000),
  EMAIL VARCHAR2(50) REFERENCES TAI_KHOAN(EMAIL)
);

CREATE TABLE HOA_DON (
  SOHD NUMBER(10) NOT NULL PRIMARY KEY,
  MATK NUMBER(10) REFERENCES TAI_KHOAN(MATK),
  MAXE NUMBER(10) REFERENCES XE(MAXE),
  SDT VARCHAR2(20) NOT NULL,
  NGAYDATXE DATE NOT NULL,
  GIODATXE TIMESTAMP NOT NULL,
  NGAYTRAXE DATE NOT NULL,
  GIOTRAXE TIMESTAMP NOT NULL,
  VITRIDATXE VARCHAR2(2000) NOT NULL,
  TONGHOADON NUMBER(10) NOT NULL,
  TRANGTHAI VARCHAR2(20) NOT NULL
);
CREATE TABLE HOP_DONG (
  MAHD NUMBER(10) NOT NULL PRIMARY KEY,
  SOHD NUMBER(10) REFERENCES HOA_DON(SOHD),
  BENA VARCHAR2(2000) NOT NULL,
  BENB VARCHAR2(2000) NOT NULL,
  NGAYLAPHOPDONG DATE NOT NULL,
  NDHD VARCHAR2(2000) NOT NULL
);
CREATE TABLE DANH_GIA (
  MADANHGIA NUMBER(10) NOT NULL PRIMARY KEY,
  MAHOPDONG NUMBER(10) REFERENCES HOP_DONG(MAHD),
  NOIDUNG VARCHAR2(2000) NOT NULL,
  NGAYTAO DATE NOT NULL,
  XEPHANG NUMBER(1) NOT NULL
);
CREATE TABLE KHIEU_NAI (
  MAKN VARCHAR2(20) NOT NULL PRIMARY KEY,
  MAHD NUMBER(10) REFERENCES HOP_DONG(MAHD),
  THONGTINKN VARCHAR2(2000) NOT NULL,
  TRANGTHAI VARCHAR2(20) NOT NULL
);